### ISSUE TITLE
segfault error when saving Biostrings output

### ISSUE THREAD

**Issue by gevro** [Bioconductor/Biostrings#103]
Hi,
I'm getting a strange segfault error that happens reproducibly for a specific chunk of my data when in my pipeline I do this:

layered.seq <- sequenceLayer(bam$seq,bam$cigar)
saveRDS(layered.seq,outputfile)

Error:
```
 *** caught segfault ***
address (nil), cause 'memory not mapped'
```

Using the latest version of Biostring 2.68.1.

Strangely, it happens only when running as an Rscript (non-interactive) but doesn't happen when interactive, so it is very hard to debug.

And it happens to only a small number of chunks that I break my dataset into, i.e. most chunks run fine.

Has anyone seen this before?

**Comment by gevro** [comment]
Note, I traced it to specific prior functions from Biostrings. But seems that upgrading from R 4.2.0 to R 4.3.1 just fixed it.

**Comment by hpages** [comment]
Glad you were able to make it work @gevro. Not much we were going to be able to do without seeing your `sessionInfo()` and having a minimal reproducible example. 

Best,
H.
