### ISSUE TITLE
Storing list of phredquality in a data.frame/table

### ISSUE THREAD

**Issue by gevro** [Bioconductor/Biostrings#105]
Hi, Is there a way to store a list of phredqualities as a column in a data.frame or data.table? I can't seem to figure out how to do this. data.frame and data.table reject the PhredQuality type, but I would imagine there should be a general way to store a list as a column regardless of the class.

**Comment by vjcitn** [comment]
S4Vectors DataFrame

**Comment by gevro** [comment]
Thanks for the info, sorry I'm not familiar with this. Are you able to share the package / command for making an S4 vectors data frame?

**Comment by gevro** [comment]
Never mind I found how to do it. With the command DataFrame.

**Comment by hpages** [comment]
@gevro Glad you figured this out. FYI questions related to the use of the Bioconductor software should preferrably be asked on the [Bioconductor support site](https://support.bioconductor.org).  Use the GitHub issue tracker for bug report or feature requests. Thanks!
