### ISSUE TITLE
Substitution matrix data not included in latest versions of Biostrings

### ISSUE THREAD

**Issue by dmacguigan** [Bioconductor/Biostrings#121]
Hello,

I'm attempting to understand why the newer versions of Biostrings have stopped including all of the substitution matrices as R data files. This will break older code that relied on these matrices.

![image](https://github.com/user-attachments/assets/f5f7ffc0-8ae5-4803-a261-307c7bc53465)

Best,
Dan

**Comment by vjcitn** [comment]
see the pwalign package   NEWS file in 3.19 states this

**Comment by hpages** [comment]
Fair enough. The matrices are back in **Biostrings** 2.74.1 (Bioc 3.20, current release) and 2.75.3 (BioC 3.21, devel), with a warning that their new home is the **pwalign** package (see commit b5de57473dd588dbf1e782c98629f8d94ea61b17).
