### ISSUE TITLE
Support for BSgenomeViews objects in matchPWM

### ISSUE THREAD

**Issue by jma1991** [Bioconductor/Biostrings#13]
Would it be possible to add a method for BSgenomeViews objects in the matchPWM function? The manual says it can take ordinary Views objects, but I don't see any support for BSgenomeViews objects?

**Comment by ahl27** [comment]
I'm going back through old bug reports to try to clean up our backlog, sorry for the long time with no feedback.
`BSgenomeViews` objects are not part of Biostrings, they're part of `BSgenome`. Adding a `matchPWM.BSgenomeViews` would have to be done in the `BSgenome` package, not in `Biostrings`.

**Comment by hpages** [comment]
Thanks @ahl27. I'm going to move this issue to the BSgenome repository.
