### ISSUE TITLE
translate gives wrong results for triplets TTG and CTG

### ISSUE THREAD

**Issue by janas-sebastien** [Bioconductor/Biostrings#15]
Hello,

Since at least Biostring 2.42, the function "translate" gives wrong results for triplets TTG and CTG.

> translate(DNAString("TTG"))
  1-letter "AAString" instance
seq: M

> translate(DNAString("CTG"))
  1-letter "AAString" instance
seq: M

=> Both should be L (leucine).

We think it's related to the erroneous default use of alternative genetic codes.

Cheers,

Seb

**Comment by janas-sebastien** [comment]
my mistake, it's considered as an alternative start codon. My issue was that the change in the behavior of the code suddenly broke our unit tests.

**Comment by janas-sebastien** [comment]
Moreover, the documentation does not say that the sequence must be a complete sequence (starting at the start codon).

**Comment by hpages** [comment]
Hi @janas-sebastien 

You're right that adding an option would have been better. Sorry for the inconvenience.

This is now done: I just added the `no.init.codon` argument to `translate()` (https://github.com/Bioconductor/Biostrings/commit/dcd915c21b96d4d981d4530f913ff9108239e129) and clarified in the documentation that, by default, `translate()` assumes that the first codon in a DNA or RNA sequence is the initiation codon. I guess it's too late to switch the default back to the old behavior.

The `no.init.codon` option is in Biostrings 2.50.1 (BioC 3.8, current release) and Biostrings 2.51.1 (BioC 3.9, current devel).

H.

**Comment by janas-sebastien** [comment]
Thanks for the fix ! Should I close that issue myself ?

**Comment by hpages** [comment]
Closing it now.
