### ISSUE TITLE
Stack smashed by writeXStringSet for FASTQ output

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Biostrings#20]
Calling `writeXStringSet` on a `DNAStringSet` with a very long element:

```r
library(Biostrings)
N <- 21000
x <- paste(sample(c("A", "C", "G", "T"), N, replace=TRUE), collapse="")
q <- runif(N)
y <- QualityScaledDNAStringSet(DNAStringSet(x), PhredQuality(q))
names(y) <- "YAY"
writeXStringSet(y, qualities=quality(y), file="whee.fastq", format="fastq")
## *** stack smashing detected ***: /home/cri.camres.org/lun01/Software/R/devel/bin/exec/R terminated
## Aborted (core dumped)
```

The exact value of `N` will probably vary between machines depending on the size of the stack, but nonetheless, this isn't good. I've tested this on BioC-devel but the same error happens on release.

<details>
<summary>Session info</summary>

```
R Under development (unstable) (2019-02-19 r76128)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /home/cri.camres.org/lun01/Software/R/trunk/lib/libRblas.so
LAPACK: /home/cri.camres.org/lun01/Software/R/trunk/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] Biostrings_2.51.2   XVector_0.23.0      IRanges_2.17.4     
[4] S4Vectors_0.21.10   BiocGenerics_0.29.1

loaded via a namespace (and not attached):
[1] zlibbioc_1.29.0 compiler_3.6.0 
```
</details>

**Comment by FelixErnst** [comment]
It crashes for me as well using a biodevel docker image (2018-12-22 r75884). I checked which value of N starts to cause the crash. `N = 20008` works, `N = 20009` does not.

**Comment by hpages** [comment]
Oops, not good! Thanks guys for the report. Will look into this ASAP.

**Comment by markb729** [comment]
This behavior also occurs in function writeQualityScaledXStringSet. While not a problem with short-read data, increasing proliferation and use of long-read data from Oxford Nanopore Technologies and Pacific Biosciences will magnify this unfortunate behavior.

**Comment by hpages** [comment]
I completely forgot about this, sorry.

Size of IO buffer increased from 20,001 to 200,000 in **Biostrings** 2.70.2 (release) and 2.71.2 (devel). See commit bcac2e61820971a3ae78af64f65cadf4f3b7b6d0

Both versions should become available to BioC users via `BiocManager::install()` on Monday.

Best,
H.
