### ISSUE TITLE
readDNAStringSet for long FASTQ files

### ISSUE THREAD

**Issue by HegedusB** [Bioconductor/Biostrings#26]
Is it possible to import ONT long reads with readDNAStringSet. I get this error message when I try it "reading FASTQ file fail//fastq_runid_1d3e3951d2d9b150a6b515f944bf47b50d01104f_0.fastq: cannot read line 10, line is too long".

**Comment by mtmorgan** [comment]
Not directly answering, but does `ShortRead::readFastq()` do the trick? When you look at the problem file, is line 10 really long, or is there a formatting problem?

**Comment by HegedusB** [comment]
Thank for the tip. The ShortRead::readFastq() can handle the fastq files.

**Comment by hpages** [comment]
`readDNAStringSet()` didn't support reads longer than 20000 bases. I changed this in [Biostrings 2.53.2](https://github.com/Bioconductor/Biostrings/commit/386666776a6df7233bf30f01b696e6870a1ef95c) so reads now can be as long as 2^31-1 bases.

Biostrings 2.53.2 should become available via `BiocManager::install()` to Bioconductor 3.10 users (current devel) in the next 48 hours.

**Comment by HegedusB** [comment]
The problem occurs only with the fastq files. With the fasta files everything worked perfectly.

**Comment by hpages** [comment]
That's expected. `readDNAStringSet(..., format="fasta")` has been supporting long sequences for many years but `readDNAStringSet(..., format="fastq")` did not until now.

**Comment by HegedusB** [comment]
Thank you very much! It is a great package, I am glad to us it.

**Comment by hpages** [comment]
You're welcome. Thanks for the kind feedback. I'm closing the issue. Feel free to re-open if you still run into problems with this with Biostrings >= 2.53.2.
