### ISSUE TITLE
writeQualityScaledXStringSet  omitted  the third line

### ISSUE THREAD

**Issue by wydty** [Bioconductor/Biostrings#36]
Hi there:
write to the fastq file use `writeQualityScaledXStringSet` function .
i want omitted  on the third line ,Is there a better way.
like `ShortRead::writeFastq(..., full = FALSE)`
```
@HWI-EAS88_1_1_1_1001_499
GGACTTTGTAGGATACCCTCGCTTTCCTTCTCCTGT
+
]]]]]]]]]]]]Y]Y]]]]]]]]]]]]VCHVMPLAS
@HWI-EAS88_1_1_1_898_392
GATTTCTTACCTATTAGTGGTTGAACAGCATCGGAC
+
]]]]]]]]]]]]Y]]]]]]]]]YPV]T][PZPICCK
```
thanks!

**Comment by hpages** [comment]
Please ask on the [Bioconductor support site](https://support.bioconductor.org). Make sure you read the Posting Guide before posting your question. In particular:
  - tag your post appropriately (Biostrings and ShortRead in that case)
  - make sure your question is clearly formulated
  - provide a small self-contained reproducible example
  - provide your `sessionInfo()`

Thanks!
