### ISSUE TITLE
FastqQuality as.matrix is overly complicated

### ISSUE THREAD

**Issue by andzandz11** [Bioconductor/Biostrings#38]
I would expect that to work:
`random_fastq_one_read %>% quality %>% as.integer`

Even the regular conversions are not working:
error:
`as.matrix(random_fastq_one_read %>% quality %>% quality %>% FastqQuality) `

I have to jump through a loop:
works:
`as(random_fastq_one_read %>% quality %>% quality %>% FastqQuality, "matrix")`

**Comment by mtmorgan** [comment]
You're right this fails terribly!

```
> random_fastq_one_read %>% quality %>% as.integer
Error in eval(lhs, parent, parent) :
  object 'random_fastq_one_read' not found
```

Can you please provide a reproducible example, for instance using files from `dir(system.file(package="Biostrings", "extdata"))` and without using pipes?

Also can you confirm that you are posting to the right repository? FastqQuality is defined in the ShortRead package.

After running `example(ShortReadQ)` I have

```
> m = as(quality(rfq), "matrix")
> class(m)
[1] "matrix" "array"
> dim(m)
[1] 256  36
```
