### ISSUE TITLE
writeXStringSet on QualityScaledDNAStringSet should automatically set qualities=

### ISSUE THREAD

**Issue by LTLA** [Bioconductor/Biostrings#43]
Consider:

```r
x1 <- DNAStringSet(c("TTGA", "CTCN"))
q1 <- PhredQuality(c("*+,-", "6789"))
qdna1 <- QualityScaledDNAStringSet(x1, q1)
names(qdna1) <- c("A", "B")

writeXStringSet(qdna1, format="fastq", file="whee.fq") # (1)
writeXStringSet(qdna1, format="fastq", file="whee.fq", qualities=quality(qdna1)) # (2) 
writeQualityScaledXStringSet(qdna1, file="whee.fq") # (3)
```

(1) has no qualities while (2) and (3) add the qualities correctly. Nonetheless, it would be a useful quality-of-life improvement for (1) to attempt to extract the qualities from `qdna1` if it is a QSDSS and `qualities=` is not explicitly provided in the function call. (2) is too verbose and it is hard to remember that (3) exists. 

In general, if you're going to provide `format="fastq"`, it would be reasonable to expect that the function would consider the qualities embedded in the supplied object, given that the qualities are the only difference from FASTA.

**Comment by FelixErnst** [comment]
This probably requires just a few minor changes. I had a look at it and it work in cdd8aa1

I am not sure, if conceptual things speak against this behavior.

**Comment by LTLA** [comment]
You'll want to avoid replacing a non-`NULL` `qualities=` if something is already specified.

**Comment by FelixErnst** [comment]
Thanks. Changed 656422a

**Comment by hpages** [comment]
sorry again that it took so long
