### ISSUE TITLE
extract the "start" position of "matchPattern"

### ISSUE THREAD

**Issue by jielab** [Bioconductor/Biostrings#53]
hi, guys:

For the following code, how could I extract the "**start**“ of the match and **calculate** the average, which will be 3?

![11](https://user-images.githubusercontent.com/26947455/128090178-e3bca347-60d6-4ea8-8274-d8785371eac1.PNG)

Thanks!

Jie

**Comment by lawremi** [comment]
Please post this question on support.bioconductor.org.
