### ISSUE TITLE
Error when trying to convert string to DNAString

### ISSUE THREAD

**Issue by evanpk** [Bioconductor/Biostrings#57]
I am getting the following error when trying to convert a string to a DNAString:

Error in as(mcols, mcols_target_class) : 
  no method or default for coercing “DFrame” to “DataTable_OR_NULL”

I reinstalled Bioconductor but no improvement. Any ideas?

**Comment by ahl27** [comment]
It's tough to know what the problem is without the code that caused the error--what was the input that caused this message?
