### ISSUE TITLE
from txdb/getSeq to fasta

### ISSUE THREAD

**Issue by madzayasodara** [Bioconductor/Biostrings#58]
Hi, I'm aiming to extract CD sequencesin fasta format by the following:
```
# load GTF
txdb <- makeTxDbFromGFF("BFgenomic.gff", format="gff")
# extract CDS
txdb.cds_by_transcript <- cdsBy(txdb, by="tx", use.names = TRUE)
dna <- readDNAStringSet("BFgenomic.fa")
# Extract CDS sequences
cds_by_trnascript <- getSeq(dna, txdb.cds_by_transcript)
# Write to fasta
writeXStringSet(cds_by_trnascript, "my.fasta")
```
but running into the error 

```
Error in writeXStringSet(cds_by_trnascript, "my.fasta") : 
  'x' must be an XStringSet object
```
What I need to maybe convert my `cds_by_trnascript`  to a `XStringSet` object?

Thank you

**Comment by lawremi** [comment]
What type of object is `cds_by_transcript`? I am guessing that it is a _DNAStringSetList_, with one _DNAString_ per contiguous CDS region. If so, you probably want to concatenate the CDS regions for each transcript, which you probably could do by calling `unstrsplit()`.

**Comment by lawremi** [comment]
Also, these types of questions are best posted to support.bioconductor.org, leaving this interface for bug reports.

**Comment by madzayasodara** [comment]
`cds_by_transcript` is _DNAStringSetList_ 
If I try:
```
LargeDNAStringSet <- DNAStringSet(lapply(cds_by_trnascript, function(x) {unlist(x)})) 
# Write to fasta
writeXStringSet(LargeDNAStringSet, "my.fasta")
```
 it complains about the NAs:

```
Error in .Call2("write_XStringSet_to_fasta", x, filexp_list, width, lkup,  : 
  'names(x)' contains NAs
```

if I try: 
`> LargeDNAStringSet <- DNAStringSet(lapply(cds_by_trnascript, function(x) {unstrsplit(x)})) `

I get:
```
Error in XVector:::new_XVectorList_from_list_of_XVector(tmp_class, x) : 
  all elements in 'x' must be DNAString objects
```
I'm ok with discarding the NAs
Thank you

**Comment by hpages** [comment]
@madzayasodara  I've answered your question about how to deal with the NA names on the support site: https://support.bioconductor.org/p/9140677/#9140683

Please use the support site for any follow up on this.

Thanks,
H.
