### ISSUE TITLE
readDNAStringSet for fasta with long headers

### ISSUE THREAD

**Issue by evaegelyng** [Bioconductor/Biostrings#59]
I am getting the error "cannot read line XX, line is too long" when opening a fasta file with readDNAStringSet. It seems to be because the headers of some sequences are very long. Would it be possible to increase the maximum header length allowed to 100 k characters with spaces or more?

Thanks,

Eva

**Comment by LafontRapnouilTristan** [comment]
Hello,

I encounter the exact same problem with a header of 25157 character in a line of my .fasta.
I just add to this issue to show that it is not an isolated problem!!
I hope you would be able to do something about it.

Thanks for the amazing work  and have a great day!
Tristan

**Comment by hpages** [comment]
I just made a change in **Biostrings** 2.70.1 (BioC 3.18) and 2.71.1 (BioC 3.19) to allow FASTA files with up to 200,000 characters (current limit was 20,000). See 35181af7b71c742ec60d36c617328c6e88aa89c4

**Biostrings** 2.70.1 should become available via `BiocManager::install()` to BioC 3.18 users in the next 24 hrs or so.

H.

**Comment by evaegelyng** [comment]
Thank you both for doing something about this issue - I found a workaround in my case, but I think the update will be useful for others working on e.g. large DNA metabarcoding datasets :-)

**Comment by hpages** [comment]
@evaegelyng You're welcome. And sorry for the long delay for addressing this.

Does the fix work for you @LafontRapnouilTristan?

**Comment by LafontRapnouilTristan** [comment]
Hi,

Thank you very much.
I seems to works for me, thanks again for the quick fix!!
We can close this issue.

Cheers!

**Comment by LafontRapnouilTristan** [comment]
Hi again,

Actually I have still one little problem but not sure how does it fit here.
I am using packages from Bioconductor on a cluster creating environment with bioconda.
The latest version of biostring is 2.68.1.
how could I or where should I ask for updating it on bioconda? 
Thanks again!

**Comment by lshep** [comment]
We don't maintain bioconda packages.  You should reach out to bioconda to update the package.  Alternatively, you should be able to install package within R by using `BiocManager::install` as well.

**Comment by LafontRapnouilTristan** [comment]
I understand, I'll try to contact bioconda or indeed do everything from R.
Many thanks!
