### ISSUE TITLE
replaceAt with VCF Object

### ISSUE THREAD

**Issue by DarioS** [Bioconductor/Biostrings#60]
It would be a nice feature if the user could create derivative DNA sequences based on variants (including indels which shift the coordinates in the string) from a VCF file. GATK4 has [FastaAlternateReferenceMaker](https://gatk.broadinstitute.org/hc/en-us/articles/360037594571-FastaAlternateReferenceMaker), but it has some important caveats.

**Comment by hpages** [comment]
If you mean implementing a `replaceAt()` method that can take a chromosome sequence and a VCF file, yeah that sounds like it would be nice but this is too high-level for **Biostrings**. **Biostrings** knows nothing about VCF files and trying to make it depend on **VariantAnnotation** (where the VCF class is defined) would not be good. **Biostrings** is intended to be a low-level infrastructure package and it should focus on that.

This should be implemented in a higher level package. Could be a dedicated package. Also I anticipate that this high level function will need a bunch of additional arguments to let the user control many aspects of this "replacement" so reusing the "replaceAt" verb might not be a great choice. You might be better off coming up with your own specialized verb.

BTW, how do you deal with this kind of ALT sequences?
```
> mcols(rowRanges(vcf))$ALT
CharacterList of length 7
[[1]] <DEL>
[[2]] C
[[3]] <DEL>
[[4]] <DEL:ME:ALU>
[[5]] <INS:ME:L1>
[[6]] <DUP>
[[7]] <DUP:TANDEM>
```

Anyways, a good start would be that you show an example of how to do this using the existing functionalities. I guess it would look something like this (sketch only):
```
library(VariantAnnotation)
fl <- system.file("extdata", "structural.vcf", package="VariantAnnotation")
vcf <- readVcf(fl, genome="hg19")

# Our goal is to infer the alternate chr1 sequence from 'vcf'.
vcf1 <- vcf[seqnames(vcf) == "1"]

# First we need to extract the IRanges from 'vcf1' that we'll pass to the 'at' argument
# of the replaceAt() call. In an ideal world, this IRanges object should be parallel to
# 'vcf1' i.e. it should have one range per variant in 'vcf1':
at <- ...

# Then we need to turn 'mcols(rowRanges(vcf1))$ALT' into some DNAStringSet object
# parallel to 'at' (and to 'vcf1'):
alt <- ...

# We're ready to call replaceAt() on chr1 from the hg19 genome:
library(BSgenome.Hsapiens.UCSC.hg19)
chr1 <- BSgenome.Hsapiens.UCSC.hg19$chr1
alt_chr1 <- replaceAt(chr1, at, alt)
```
This would be a nice example to add to the man page for `replaceAt()` (**Biostrings** would need to suggest **VariantAnnotation**).

Want to give it a try?

H.

**Comment by DarioS** [comment]
Looking more closely at the examples, they are already quite long and demonstrate both insertions and deletions. The Arguments section mentions:

> This is useful when using replaceAt to perform insertions.

but nothing about deletions, which made me assume that `replaceAt` couldn't do deletions for some obscure reason.

 I think I got distracted by the parameter descriptions in Arguments section mentioning virtual classes a lot when they could have just directly mentioned `IRanges` and `IRangesList` instead of their superclasses. Perhaps replace them for clarity?

The VCF example above reminds me that VCF format quickly gets messy and different tools have different interpretations of what a valid VCF contains. There is no official file format validator for it. It is probably best not to offer an explicit `replaceAt` method for VCF. There even appears to be an effort to publish [a new version of the VCF specifications](https://github.com/samtools/hts-specs/milestone/5) with numerous changes.

**Comment by hpages** [comment]
> This is useful when using replaceAt to perform insertions.

Taking things out of context doesn't help. "This" here refers to the feature that `at` can be specified as a numeric vector of positions instead of an IRanges object to specify zero-width ranges. And since zero-width ranges are associated with insertions,  "this" is useful when using `replaceAt()` to perform insertions. Here is the full explanation of this feature provided in the man page:

>      at: Typically a IntegerRanges object if ‘x’ is an XString object,
>           and an IntegerRangesList object if ‘x’ is an XStringSet
>           object.
>
>           Alternatively, the ranges can be specified with only 1 number
>           per range (its start position), in which case they are
>           considered to be empty ranges (a.k.a. zero-width ranges). So
>           if ‘at’ is a numeric vector, an IntegerList object, or a list
>           of numeric vectors, each number in it is interpreted as the
>           start position of a zero-width range.  This is useful when
>           using ‘replaceAt’ to perform insertions.

H.

**Comment by DarioS** [comment]
Thanks, I was reading "Typically a IntegerRanges/IntegerRangesList object" and at first not interpreting that is by inheritance (i.e. a user can't create an instance of IntegerRanges but can do with IRanges). ?IntegerRangesList has a nice tree diagram and discusses which class is abstract and which is concrete but ?IntegerRanges contains a stub to be filled in, which I looked at first. Anyway, original feature request is solved for simple SNPs and indels use case.
