### ISSUE TITLE
Error in .Call2("new_XStringSet_from_CHARACTER", class(x0), elementType(x0),  :    key 50 (char '2') not in lookup table

### ISSUE THREAD

**Issue by safiqu** [Bioconductor/Biostrings#68]
I am trying to use customised data base.

Code 👍 
"tax <- addSpecies(seqtab.nochim, refFasta = "/srv/SP_Pro_acnes.fa")"

Error: 
"Error in .Call2("new_XStringSet_from_CHARACTER", class(x0), elementType(x0),  : 
  key 50 (char '2') not in lookup table"

My species fasta file looks like this:
>ID001 Cutibacterium acnesA1
GTTGCACACCAGGGGGTCAACTTGGCGTCCTCAGTTCAAAATTGATTCAAACTAACAGTTCCATGTCGGGAAACAGCACCAGGAAGCTCGTGACAT
>ID002 Cutibacterium acnesA10
GTTGCACACCAGGGGGTCAACTTGGCGTCCTCAGTTCAAAATTGATTCAAACTAACAGTTCCATGCCGGGAAACAGCACCAGGAAGCTCGTGACA

I did not get it what I need to improve in dada2 pipeline or fasta files

**Comment by hpages** [comment]
This is a question for the **dada2** authors/maintainers and you should ask it on [the Bioconductor support site](https://support.bioconductor.org). Make sure to: (1) tag your question properly, (2) provide a reproducible example (the above code is not), and (3) format your code properly (by putting it between ` ``` ` lines).

Thanks,
H.
