### ISSUE TITLE
AAString does not convert strings to upper case

### ISSUE THREAD

**Issue by stitam** [Bioconductor/Biostrings#84]
Hi,

I have noticed the following small inconsistency:

While `DNAString` automatically converts a lower case strings to upper case:
``` r
Biostrings::DNAString("atgc")
#> 4-letter DNAString object
#> seq: ATGC
```
<sup>Created on 2022-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

`AAString` (and `AAStringSet`) does not:
``` r
Biostrings::AAString("mkig")
#> 4-letter AAString object
#> seq: mkig
```

<sup>Created on 2022-09-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The impact of this inconsistency is that some other packages seem to depend on upper case characters and may fail sporadically if I am not careful. I understand this issue can be fixed from multiple sides but I am wondering if it would be possible for `AAString()` and `AAStringset()` to enforce upper case characters, similarly to `DNAString()` and `DNAStringSet()`? Many thanks.

**Comment by ahl27** [comment]
Fix for this is in PR #97
